name: deseure_steven_card
description: business card
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.0
  url_launcher: ^5.7.10
  flutter_phone_direct_caller: ^1.0.1
  flutter_pdfview: ^1.0.3+5
  path_provider: ^1.6.24
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/steven.jpg
    - assets/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Sourse Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: Cv
      fonts:
        - asset: fonts/Cv.ttf

    - family: CvOne
      fonts:
       - asset: fonts/CvOne.ttf
