/// Flutter icons CvOne
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CvOne
///      fonts:
///       - asset: fonts/CvOne.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CvOne {
  CvOne._();

  static const _kFontFam = 'CvOne';
  static const _kFontPkg = null;

  static const IconData curriculum_vitae__4_ =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
